title: <style="text-align: center;> Mason Ham's Portfolio of Cybersecurity Projects <br>and Write-ups.
description: Hacker is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
