title: Mason Ham's Portfolio of Cybersecurity Projects and Write-ups.
description: Hacker is a theme for GitHub Pages.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
exclude:
  - Malware-Reports/reports.md
